name: work_with_date_and_time
authors:
  - Piotr Hariuc <acvatoris@gmail.com>
description: A Dart library for working with date and time.
version: 0.0.1
homepage: https://github.com/hariuc/work_with_date_and_time

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:


dev_dependencies:
  flutter_lints: ^1.0.0


